// Nội dung trang theo ngôn ngữ. Sửa chữ ở đây, không cần đụng vào component.
export const AMAZON_URL = "https://a.co/d/0jbHvq34";
export const AUTHOR_URL = "https://www.linkedin.com/in/dangtrunganh";
export const LINKEDIN_URL = "https://www.linkedin.com/build-relation/newsletter-follow?entityUrn=7512726408108924930";

// Bản tiếng Nhật (/ja/) đang ẩn: không có cờ trong LangSwitcher, không nằm trong hreflang,
// không tự chuyển theo múi giờ, mọi trang đều noindex. Người đọc Nhật theo dõi trên note và chia sẻ lên X.
export const NOTE_URL = process.env.NEXT_PUBLIC_NOTE_URL || "https://note.com/dangtrunganh/m/me3f2ade9009d";

// Bản tiếng Trung giản thể (/zh/) cũng đang ẩn, y như bản tiếng Nhật. LinkedIn không dùng được ở Trung Quốc đại lục:
// người đọc theo dõi qua tài khoản công chúng WeChat (bài viết hoặc trang mã QR) khi đã có, chia sẻ lên Weibo.
export const WECHAT_URL = process.env.NEXT_PUBLIC_WECHAT_URL || "";

/** Các ngôn ngữ công khai (hiện cờ trong LangSwitcher) */
export const LANGS = ["vi", "en", "es"] as const;
/** Các bản ẩn: noindex, không hreflang, không cờ, không tự chuyển theo múi giờ, không có link từ bản công khai */
export const HIDDEN_LANGS = ["ja", "zh"] as const;
/** Mọi ngôn ngữ có trang, kể cả bản ẩn */
export const ALL_LANGS = [...LANGS, ...HIDDEN_LANGS] as const;
export type Lang = (typeof ALL_LANGS)[number];
export type HiddenLang = (typeof HIDDEN_LANGS)[number];

export const isHidden = (lang: Lang): lang is HiddenLang => (HIDDEN_LANGS as readonly Lang[]).includes(lang);

/** Nút theo dõi/đăng ký: bản tiếng Nhật dùng note, bản tiếng Trung dùng WeChat khi đã có; chưa có thì tạm dùng bản tin LinkedIn */
export function followUrl(lang: Lang) {
  if (lang === "ja" && NOTE_URL) return NOTE_URL;
  if (lang === "zh" && WECHAT_URL) return WECHAT_URL;
  return LINKEDIN_URL;
}

/** Nhãn nút theo dõi của bản tiếng Trung, đổi theo việc đã có tài khoản WeChat hay chưa */
export const ZH_FOLLOW = WECHAT_URL ? "关注微信公众号" : "公众号筹备中·暂可在LinkedIn订阅";

const ZH_NOTE = WECHAT_URL
  ? `新章节会在微信公众号上第一时间发布。<a href="${WECHAT_URL}" target="_blank" rel="noopener noreferrer">关注公众号</a>`
  : `中文版的微信公众号正在筹备中。在此之前，可以通过<a href="${LINKEDIN_URL}" target="_blank" rel="noopener noreferrer">LinkedIn通讯</a>（英文、越南文）追读后续章节。`;

/** Nhãn nút theo dõi của bản tiếng Nhật, đổi theo việc đã có trang note hay chưa */
export const JA_FOLLOW = NOTE_URL ? "noteでフォローする" : "note準備中・いまはLinkedInで購読";

const JA_NOTE = NOTE_URL
  ? `新しい章はnoteでお知らせします。<a href="${NOTE_URL}" target="_blank" rel="noopener noreferrer">noteをフォローする</a>`
  : `日本語版の連載はnoteで準備中です。それまでは<a href="${LINKEDIN_URL}" target="_blank" rel="noopener noreferrer">LinkedInのニュースレター</a>（英語・ベトナム語）で続きを追えます。`;

export const content = {
  "vi": {
    "cont": "Đọc tiếp chương 1",
    "other_lang": {"en":"Mở bản tiếng Anh","vi":"Mở bản tiếng Việt","es":"Mở bản tiếng Tây Ban Nha","ja":"Mở bản tiếng Nhật","zh":"Mở bản tiếng Trung"},
    "title": "Mười phần trăm còn lại",
    "eyebrow": "Truyện quản trị · Mỗi tuần một chương",
    "h1": "Mười phần trăm <em>còn lại</em>",
    "q": "Khi agent làm gần hết mọi việc, con người lớn lên từ đâu?",
    "buy": "Đặt trước trên Amazon",
    "read": "Đọc thử chương 1",
    "note": "Mỗi tuần một chương mới. <a href=\"https://www.linkedin.com/build-relation/newsletter-follow?entityUrn=7512726408108924930\" target=\"_blank\" rel=\"noopener noreferrer\">Đăng ký bản tin trên LinkedIn</a>",
    "alt": "Bìa sách Mười phần trăm còn lại: ba người đứng trên mỏm đá nhìn về ngọn hải đăng bên bờ sông",
    "quote": "“Ở Hải Đăng, agent làm <b>chín mươi phần trăm</b> công việc. Thắng Tất lo <b>mười phần trăm còn lại</b>.”",
    "leg1": "<b>90 chấm</b> là phần việc agent làm",
    "leg2": "<b>10 chấm</b> là phần còn lại của con người",
    "st_eb": "Câu chuyện",
    "st_h": "Một công ty cho thuê AI agent, và mười hai con người phía sau",
    "st1": "Hải Đăng cho thuê AI agent theo tháng. Khách hàng của họ là hơn mười nghìn công ty chỉ có một CEO: một chủ tiệm len, một nha sĩ, một xưởng may nhỏ, mỗi người cùng một đội agent ghi sổ, chào khách, trả lời tin nhắn lúc nửa đêm.",
    "st2": "Phía sau nền tảng ấy, số người thật chỉ vừa đủ ngồi kín hai dãy bàn. Họ đón những ca agent không giải quyết được. Và họ bắt đầu tự hỏi: nếu máy làm được chín mươi phần trăm việc của mình, thì mười phần trăm còn lại là gì?",
    "st3": "Cuốn sách đặt những bài học cũ về cách con người làm việc với nhau vào một thế giới mà người viết ra chúng chưa từng hình dung. Phần lớn, chúng còn đúng hơn.",
    "ca_eb": "Những người ở dãy bàn thứ hai",
    "ca_h": "Ba người sẽ đi cùng bạn suốt cuốn sách",
    "r1": "Nhân vật chính",
    "d1": "Hai năm kinh nghiệm, làm việc nhanh, đứng thứ tư bảng xếp hạng tốc độ. Mọi thứ đều ổn, đến mức anh không còn gì để ghi vào cuốn sổ.",
    "r2": "Người của những ngày đầu",
    "d2": "Một trong những người đầu tiên của Hải Đăng. Ít nói, nhưng nhớ từng khách hàng đã phải báo đến lần thứ ba.",
    "r3": "Trưởng nhóm",
    "d3": "Gần hai mươi năm đi làm, từ thời tổng đài toàn người trực đến thời agent làm gần hết. Luôn mang theo một cuốn sách cũ sờn gáy, và chỉ thích nói chuyện ở những chỗ không có bàn họp.",
    "a1k": "Mở đầu mỗi chương",
    "a1h": "Một câu chuyện ở Hải Đăng",
    "a1p": "Một ca khó, một cuộc họp, một buổi chiều bên bờ sông.",
    "a2k": "Xen giữa",
    "a2h": "Góc lý thuyết",
    "a2p": "Câu chuyện đặt cạnh một nghiên cứu quản trị đã được kiểm chứng, từ Kaizen của Toyota đến an toàn tâm lý.",
    "a3k": "Cuối chương",
    "a3h": "Dành cho bạn",
    "a3p": "Vài câu hỏi để mang về công việc của chính mình.",
    "toc_eb": "Mục lục",
    "toc_h": "Hai mươi chương, từ một con người đến cả công ty",
    "ready": "Đọc được ngay",
    "soon": "Sắp ra mắt",
    "p1": "Phần I · Người còn thấy đau",
    "p2": "Phần II · Đội nhỏ, việc lớn",
    "p3": "Phần III · Khi công ty lớn lên",
    "p4": "Phần IV · Mười phần trăm còn lại",
    "c": [
      "Chỗ đau",
      "Người nhập cư",
      "Ngày hôm nay giống hôm qua",
      "Bán một ý tưởng",
      "Việc khó như nam châm",
      "Người khác mình",
      "Đúng người trên xe",
      "Khen ngay, chê thật",
      "Giao mục tiêu, không giao cách làm",
      "Bệnh của người số một",
      "Thợ thủ công",
      "Dò đá qua sông",
      "Khách hàng không phải KPI",
      "Nỗi sợ của sự to ra",
      "Văn hóa lấp lỗ hổng",
      "Nghịch lý của tự động hóa",
      "Người nghe giỏi",
      "Sợ hãi vừa đủ",
      "Hàng ghế cuối",
      "Người kế tiếp"
    ],
    "th": [
      "Kaizen · thắng lợi nhỏ",
      "Học vòng kép · luyện tập có chủ đích",
      "Thiên kiến hiện trạng · tư duy phát triển",
      "An toàn tâm lý · Jobs to Be Done",
      "Thuyết đặt mục tiêu · thưởng cho A mà mong B",
      "Khác biệt thắng năng lực · tư duy bầy đàn",
      "“Ai trước, việc sau” · trí tuệ tập thể",
      "Thẳng thắn triệt để · văn hóa công bằng",
      "Chỉ huy theo sứ mệnh · động lực tự thân",
      "Thế lưỡng nan của nhà đổi mới",
      "Người thợ thủ công · tay nghề",
      "Ra quyết định nhanh khi chưa đủ thông tin",
      "Định luật Goodhart",
      "Các giai đoạn tăng trưởng của tổ chức",
      "Ba tầng văn hóa",
      "Nghịch lý của tự động hóa",
      "Lắng nghe để người khác thay đổi",
      "“Chỉ kẻ đa nghi mới sống sót”",
      "Quản lý bằng cách đi quanh",
      "Lãnh đạo trưởng thành từ bên trong"
    ],
    "ending": "<b>Lời kết · Nơi nào có ý chí.</b> Một buổi chiều nữa bên bờ sông, nhưng lần này người cầm cuốn sách cũ là Thắng Tất.",
    "ex_eb": "Đọc thử · Chương 1",
    "ex_h": "Chỗ đau",
    "ex_sub": "Lần báo thứ ba",
    "ex_more": "Chương 1 đến {n} đã ra trên LinkedIn. Sách phát hành ngày 31/12/2026, đã mở đặt trước trên Amazon.",
    "full": "Đặt trước sách",
    "sub": "Đăng ký trên LinkedIn",
    "f_eb": "Theo dõi câu chuyện",
    "f_h": "Mỗi tuần, một chương mới",
    "f_p": "Đọc xong chương nào mà bạn muốn cãi lại Trung, hay bênh vực Thắng Tất, thì cuốn sách đã làm được việc của nó.",
    "o1k": "Sách",
    "o1v": "<i>The Last 10%</i> phát hành ngày 31/12/2026",
    "o1b": "Đặt trước trên Amazon",
    "o2k": "Từng chương, miễn phí",
    "o2v": "Nhận chương mới mỗi tuần qua bản tin <i>Mười phần trăm còn lại</i>",
    "o2b": "Đăng ký trên LinkedIn",
    "ft": "Hải Đăng và các nhân vật trong sách đều là hư cấu.",
    "excerpt": [
      "Ở Hải Đăng, agent làm chín mươi phần trăm công việc. Thắng Tất lo mười phần trăm còn lại.",
      "Hải Đăng cho thuê AI agent. Khách hàng của họ là một kiểu doanh nghiệp mới mọc lên vài năm gần đây, nhiều như nấm sau mưa: công ty chỉ có một người. Một CEO duy nhất, và quanh người ấy là cả một đội agent thuê theo tháng. Agent kế toán ghi sổ. Agent bán hàng chào khách. Agent chăm sóc trả lời tin nhắn lúc nửa đêm. Agent nhập hàng đặt len, đặt vải, đặt giấy in. Hơn mười nghìn công ty như thế đang chạy trên nền tảng của Hải Đăng, ngày cũng như đêm. Còn phía sau nền tảng ấy, số người thật chỉ vừa đủ ngồi kín hai dãy bàn.",
      "Trần Thắng Tất ngồi ở dãy thứ hai, trong nhóm vận hành khách hàng. Việc của anh là đón những ca agent không tự giải quyết được, hoặc những ca CEO không hài lòng với cách agent đã giải quyết. Mỗi ca như vậy hiện lên màn hình kèm một tiếng chuông ngắn, khô, giống tiếng thìa gõ vào thành cốc. Hai năm nay, mỗi ngày chừng một trăm tiếng như thế. Có những đêm nằm trong bóng tối, anh vẫn nghe nó vang lên đâu đó trong đầu, rồi tắt.",
      "Anh làm việc nhanh. Một đoạn hội thoại dài giữa CEO và agent, anh lướt qua trong vài giây là thấy ngay agent đã hiểu sai ở câu nào. Chỉnh cấu hình, đóng phiếu, nhận ca tiếp theo. Bảng xếp hạng tuần trước để tên anh ở vị trí thứ tư về tốc độ. Anh không phải người giỏi nhất, nhưng cũng chưa từng có ai phàn nàn gì về anh.",
      "Mọi thứ đều ổn. Và chính điều đó mới là vấn đề, chỉ là lúc ấy anh chưa biết.",
      "Ngày đầu đi làm, anh hồi hộp đến mức đọc từng dòng suy luận của agent như đọc một cuốn truyện trinh thám. Anh ghi kín ba trang sổ về những kiểu lỗi agent hay mắc, hỏi đi hỏi lại chị huấn luyện vì sao agent bán hàng cứ chào khách bằng một giọng trang trọng đến lạ. Bây giờ cuốn sổ nằm im trong ngăn kéo, bìa phủ một lớp bụi mỏng. Anh không còn mở nó ra nữa. Anh không còn gì để ghi."
    ]
  },
  "en": {
    "cont": "Keep reading Chapter 1",
    "other_lang": {"en":"Opens in English","vi":"Opens in Vietnamese (not yet translated)","es":"Opens in Spanish","ja":"Opens in Japanese","zh":"Opens in Chinese"},
    "title": "The Last 10%",
    "eyebrow": "A management novel · One chapter a week",
    "h1": "The Last <em>10%</em>",
    "q": "When AI agents do almost everything, where do people still grow?",
    "buy": "Pre-order on Amazon",
    "read": "Read Chapter 1",
    "note": "New chapters every week. <a href=\"https://www.linkedin.com/build-relation/newsletter-follow?entityUrn=7512726408108924930\" target=\"_blank\" rel=\"noopener noreferrer\">Subscribe to the newsletter on LinkedIn</a>",
    "alt": "Cover of The Last 10%: three people on a rocky ledge looking toward a lighthouse by the river",
    "quote": "“At Hải Đăng, agents did <b>ninety percent</b> of the work. Thắng Tất handled <b>the last ten</b>.”",
    "leg1": "<b>90 dots</b>: the work agents do",
    "leg2": "<b>10 dots</b>: the part that is still human",
    "st_eb": "The story",
    "st_h": "A company that rents out AI agents, and the twelve people behind it",
    "st1": "Hải Đăng, Vietnamese for “lighthouse”, rents out AI agents by the month. Its customers are more than ten thousand companies run by a single CEO: a yarn shop owner, a dentist, a small garment workshop, each with a team of agents that keep the books, greet customers and answer messages at midnight.",
    "st2": "Behind the platform, the actual humans barely fill two rows of desks. They take the cases the agents cannot solve. And they have started to wonder: if a machine can do ninety percent of my job, what is the other ten percent?",
    "st3": "The book places old lessons about how people work together in a world their authors never imagined. Mostly, they hold even better.",
    "ca_eb": "The second row of desks",
    "ca_h": "Three people who walk with you through the whole book",
    "r1": "The protagonist",
    "d1": "Two years in, fast at his job, fourth on the speed leaderboard. Everything is fine, so fine that he has nothing left to write in his notebook.",
    "r2": "One of the first hires",
    "d2": "Among the first people at Hải Đăng. Quiet, but he remembers every customer who had to report something a third time.",
    "r3": "The team lead",
    "d3": "Almost twenty years of work, from call centres staffed entirely by people to the age of agents. Always carries a worn old book, and only likes to talk in places with no meeting tables.",
    "a1k": "Each chapter opens with",
    "a1h": "A story at Hải Đăng",
    "a1p": "A hard case, a meeting, an afternoon by the river.",
    "a2k": "Woven through",
    "a2h": "Theory corners",
    "a2p": "The story set beside well-tested management research, from Toyota’s Kaizen to psychological safety.",
    "a3k": "Each chapter ends with",
    "a3h": "For you",
    "a3p": "A few questions to take back to your own work.",
    "toc_eb": "Contents",
    "toc_h": "Twenty chapters, from one person to a whole company",
    "ready": "Read now",
    "soon": "Coming soon",
    "p1": "Part I · Those Who Still Feel It",
    "p2": "Part II · Small Team, Big Work",
    "p3": "Part III · When the Company Grows Up",
    "p4": "Part IV · The Last 10%",
    "c": [
      "Where It Hurts",
      "The Immigrant",
      "Today, Like Yesterday",
      "Selling an Idea",
      "Hard Problems Are Magnets",
      "People Unlike Us",
      "The Right People on the Bus",
      "Praise Now, Criticize Honestly",
      "Give Goals, Not Methods",
      "The Number-One Disease",
      "The Craftsman",
      "Feeling for the Stones",
      "Customers Are Not KPIs",
      "The Fear of Getting Big",
      "Culture Fills the Gaps",
      "The Irony of Automation",
      "The Good Listener",
      "Just Enough Fear",
      "The Back Row",
      "The Next One"
    ],
    "th": [
      "Kaizen · small wins",
      "Double-loop learning · deliberate practice",
      "Status quo bias · growth mindset",
      "Psychological safety · Jobs to Be Done",
      "Goal-setting theory · rewarding A, hoping for B",
      "Diversity beats ability · groupthink",
      "“First who, then what” · collective intelligence",
      "Radical Candor · just culture",
      "Mission command · intrinsic motivation",
      "The innovator’s dilemma",
      "The craftsman · pride in work",
      "Fast decisions with incomplete information",
      "Goodhart’s law",
      "How organizations grow",
      "Three levels of culture",
      "The ironies of automation",
      "Listening that helps people change",
      "“Only the paranoid survive”",
      "Management by walking around",
      "Leaders grown from within"
    ],
    "ending": "<b>Epilogue · Where There Is a Will.</b> One more afternoon by the river, but this time it is Thắng Tất holding the old book.",
    "ex_eb": "Sample · Chapter 1",
    "ex_h": "Where It Hurts",
    "ex_sub": "The Third Report",
    "ex_more": "Chapters 1 to {n} are out. The book comes out on December 31, 2026, and is open for pre-order on Amazon.",
    "full": "Pre-order the book",
    "sub": "Subscribe on LinkedIn",
    "f_eb": "Follow the story",
    "f_h": "A new chapter every week",
    "f_p": "If you finish a chapter wanting to argue with Trung, or to stand up for Thắng Tất, the book has done its job.",
    "o1k": "The book",
    "o1v": "<i>The Last 10%</i> comes out December 31, 2026",
    "o1b": "Pre-order on Amazon",
    "o2k": "Chapter by chapter, free",
    "o2v": "Get each new chapter through the LinkedIn newsletter",
    "o2b": "Subscribe on LinkedIn",
    "ft": "Hải Đăng and all characters in the book are fictional.",
    "excerpt": [
      "At Hải Đăng, agents did ninety percent of the work. Thắng Tất handled the last ten.",
      "Hải Đăng, Vietnamese for “lighthouse”, rented out AI agents. Its customers were a new kind of business that had sprung up over the past few years: the one-person company. A single CEO, backed by a team of agents rented by the month. An accounting agent, a sales agent, a customer care agent, a purchasing agent. More than ten thousand companies like that ran on Hải Đăng’s platform. Behind the platform, the actual humans barely filled two rows of desks.",
      "Trần Thắng Tất sat in the second row, on the customer operations team. His job was to handle the cases agents couldn’t resolve on their own, or the ones where a CEO didn’t like how an agent had resolved them. Each case arrived on his screen with a short chime. Two years, about a hundred chimes a day. So many that some nights, lying in bed, he could still hear them.",
      "Thắng Tất was fast. He could read a conversation between a CEO and an agent in seconds, spot exactly where the agent had misunderstood, fix the configuration and close the ticket. Last week’s leaderboard ranked him fourth for handling time. He wasn’t the best, but nobody ever complained about him either.",
      "And that was the problem. Everything was fine.",
      "On his first day, Thắng Tất had been so nervous he read every line of an agent’s reasoning like a detective novel. He filled three pages of a notebook with the kinds of mistakes agents tended to make, and kept asking the trainer why the sales agent greeted customers so stiffly. Now the notebook sat in a drawer, its cover gathering dust. He didn’t need it anymore."
    ]
  },
  "es": {
    "cont": "Seguir leyendo el capítulo 1",
    "other_lang": {"en":"Se abre en inglés","vi":"Se abre en vietnamita (aún sin traducir)","es":"Se abre en español","ja":"Se abre en japonés","zh":"Se abre en chino"},
    "title": "El último 10 %",
    "eyebrow": "Novela de management · Un capítulo por semana",
    "h1": "El último <em>10 %</em>",
    "q": "Cuando los agentes de IA hacen casi todo, ¿dónde siguen creciendo las personas?",
    "buy": "Reservar en Amazon",
    "read": "Leer el capítulo 1",
    "note": "Un capítulo nuevo cada semana. <a href=\"https://www.linkedin.com/build-relation/newsletter-follow?entityUrn=7512726408108924930\" target=\"_blank\" rel=\"noopener noreferrer\">Suscríbete al boletín en LinkedIn</a>",
    "alt": "Portada de The Last 10%: tres personas sobre una roca miran hacia un faro junto al río",
    "quote": "“En Hải Đăng, los agentes hacían <b>el noventa por ciento</b> del trabajo. Thắng Tất se ocupaba <b>del diez restante</b>.”",
    "leg1": "<b>90 puntos</b>: el trabajo que hacen los agentes",
    "leg2": "<b>10 puntos</b>: la parte que sigue siendo humana",
    "st_eb": "La historia",
    "st_h": "Una empresa que alquila agentes de IA, y las doce personas que hay detrás",
    "st1": "Hải Đăng, que en vietnamita significa “faro”, alquila agentes de IA por meses. Sus clientes son más de diez mil empresas dirigidas por un solo CEO: una tienda de lanas, una clínica dental, un pequeño taller de confección, cada uno con un equipo de agentes que lleva la contabilidad, atiende a los clientes y responde mensajes a medianoche.",
    "st2": "Detrás de la plataforma, las personas de carne y hueso apenas llenan dos filas de escritorios. Se encargan de los casos que los agentes no saben resolver. Y han empezado a preguntarse: si una máquina puede hacer el noventa por ciento de mi trabajo, ¿qué es el diez por ciento restante?",
    "st3": "El libro lleva viejas lecciones sobre cómo trabajamos juntos a un mundo que sus autores nunca imaginaron. Casi siempre, resultan aún más ciertas.",
    "ca_eb": "La segunda fila de escritorios",
    "ca_h": "Tres personas que te acompañarán durante todo el libro",
    "r1": "El protagonista",
    "d1": "Dos años en la empresa, rápido, cuarto en la clasificación de velocidad. Todo va bien, tan bien que ya no le queda nada que anotar en su cuaderno.",
    "r2": "De los primeros",
    "d2": "Una de las primeras personas de Hải Đăng. Habla poco, pero recuerda a cada cliente que tuvo que avisar por tercera vez.",
    "r3": "El jefe de equipo",
    "d3": "Casi veinte años de oficio, desde las centralitas atendidas solo por personas hasta la era de los agentes. Siempre lleva un libro viejo con el lomo gastado, y solo le gusta conversar donde no hay mesas de reuniones.",
    "a1k": "Cada capítulo empieza con",
    "a1h": "Una historia en Hải Đăng",
    "a1p": "Un caso difícil, una reunión, una tarde junto al río.",
    "a2k": "Entremedias",
    "a2h": "Rincones de teoría",
    "a2p": "La historia junto a una investigación de gestión contrastada, del Kaizen de Toyota a la seguridad psicológica.",
    "a3k": "Cada capítulo termina con",
    "a3h": "Para ti",
    "a3p": "Unas preguntas para llevarte a tu propio trabajo.",
    "toc_eb": "Índice",
    "toc_h": "Veinte capítulos, de una persona a toda una empresa",
    "ready": "Disponible",
    "soon": "Próximamente",
    "p1": "Parte I · Quienes aún sienten el dolor",
    "p2": "Parte II · Equipo pequeño, gran trabajo",
    "p3": "Parte III · Cuando la empresa crece",
    "p4": "Parte IV · El último 10 %",
    "c": [
      "Donde duele",
      "El inmigrante",
      "Hoy, igual que ayer",
      "Vender una idea",
      "Los retos difíciles son imanes",
      "Gente distinta a nosotros",
      "Las personas adecuadas en el autobús",
      "Elogiar al momento, criticar con sinceridad",
      "Dar objetivos, no métodos",
      "La enfermedad del número uno",
      "El artesano",
      "Tantear las piedras",
      "Los clientes no son KPI",
      "El miedo a crecer",
      "La cultura llena los huecos",
      "La ironía de la automatización",
      "El buen oyente",
      "El miedo justo",
      "La última fila",
      "El siguiente"
    ],
    "th": [
      "Kaizen · pequeñas victorias",
      "Aprendizaje de doble ciclo · práctica deliberada",
      "Sesgo del statu quo · mentalidad de crecimiento",
      "Seguridad psicológica · Jobs to Be Done",
      "Teoría del establecimiento de metas · premiar A esperando B",
      "La diversidad supera a la capacidad · pensamiento grupal",
      "“Primero quién, después qué” · inteligencia colectiva",
      "Franqueza radical · cultura justa",
      "Mando por misión · motivación intrínseca",
      "El dilema del innovador",
      "El artesano · orgullo por el oficio",
      "Decidir rápido sin toda la información",
      "Ley de Goodhart",
      "Cómo crecen las organizaciones",
      "Tres niveles de la cultura",
      "Las ironías de la automatización",
      "Escuchar para ayudar a cambiar",
      "“Solo los paranoicos sobreviven”",
      "Gestión caminando",
      "Líderes formados desde dentro"
    ],
    "ending": "<b>Epílogo · Donde hay voluntad.</b> Otra tarde junto al río, pero esta vez quien sostiene el viejo libro es Thắng Tất.",
    "ex_eb": "Adelanto · Capítulo 1",
    "ex_h": "Donde duele",
    "ex_sub": "El tercer aviso",
    "ex_more": "Ya se publicaron los capítulos 1 a {n}. El libro sale el 31 de diciembre de 2026 y ya puedes reservarlo en Amazon.",
    "full": "Reservar el libro",
    "sub": "Suscribirse en LinkedIn",
    "f_eb": "Sigue la historia",
    "f_h": "Un capítulo nuevo cada semana",
    "f_p": "Si terminas un capítulo con ganas de discutir con Trung, o de defender a Thắng Tất, el libro ha cumplido su función.",
    "o1k": "El libro",
    "o1v": "<i>The Last 10%</i> sale el 31 de diciembre de 2026",
    "o1b": "Reservar en Amazon",
    "o2k": "Capítulo a capítulo, gratis",
    "o2v": "Recibe cada capítulo nuevo en el boletín de LinkedIn",
    "o2b": "Suscribirse en LinkedIn",
    "ft": "Hải Đăng y todos los personajes del libro son ficticios.",
    "excerpt": [
      "En Hải Đăng, que en vietnamita significa ‘faro’, los agentes hacían el noventa por ciento del trabajo. Thắng Tất se ocupaba del diez por ciento restante.",
      "Hải Đăng alquilaba agentes de IA. Sus clientes eran un tipo nuevo de empresa que en los últimos años había brotado como hongos después de la lluvia: la empresa de una sola persona. Un único CEO y, a su alrededor, todo un equipo de agentes alquilados por mes. El agente contable llevaba los libros. El agente de ventas atendía a los clientes. El agente de atención respondía mensajes a medianoche. El agente de compras pedía lana, tela, papel para imprimir. Más de diez mil empresas así funcionaban sobre la plataforma de Hải Đăng, de día y de noche. Detrás de esa plataforma, las personas de carne y hueso apenas alcanzaban para llenar dos filas de escritorios.",
      "Trần Thắng Tất se sentaba en la segunda fila, en el equipo de operaciones con clientes. Su trabajo era recibir los casos que los agentes no lograban resolver por sí mismos, o aquellos en los que el CEO no estaba conforme con cómo el agente los había resuelto. Cada caso aparecía en su pantalla acompañado de un timbre corto y seco, como una cucharita golpeando el borde de un vaso. Desde hacía dos años, unos cien timbres así cada día. Había noches en que, acostado en la oscuridad, todavía lo oía sonar en algún lugar de su cabeza, y luego apagarse.",
      "Trabajaba rápido. Una conversación larga entre un CEO y un agente le bastaba recorrerla en unos segundos para ver en qué frase el agente había entendido mal. Ajustar la configuración, cerrar el ticket, tomar el siguiente caso. La tabla de la semana anterior ponía su nombre en el cuarto lugar en velocidad. No era el mejor, pero tampoco nadie se había quejado nunca de él.",
      "Todo estaba bien. Y ese era justamente el problema, solo que en ese momento él todavía no lo sabía.",
      "Su primer día de trabajo estaba tan nervioso que leía cada línea del razonamiento de los agentes como si fuera una novela policial. Llenó tres páginas de un cuaderno con los tipos de errores que solían cometer los agentes, y le preguntaba una y otra vez a la instructora por qué el agente de ventas saludaba a los clientes con un tono tan extrañamente solemne. Ahora el cuaderno dormía en un cajón, con la tapa cubierta por una fina capa de polvo. Ya no lo abría. Ya no tenía nada que anotar."
]
  },
  // Bản tiếng Nhật (ẩn, mới có chương 1). Tên sách 『残りの10%』, nhân vật タット・チュンさん, công ty ハイダン社.
  "ja": {
    "cont": "第1章のつづきを読む",
    "other_lang": {"en":"英語版で開きます（日本語訳は準備中）","vi":"ベトナム語の原書で開きます（日本語訳は準備中）","es":"スペイン語版で開きます","ja":"日本語版で開きます","zh":"中国語版で開きます"},
    "title": "残りの10%",
    "eyebrow": "AI時代のマネジメント小説",
    "h1": "残りの<em>10%</em>",
    "q": "AIエージェントが仕事の九割をこなす時代、人間に残る一割とは何か。",
    "buy": "英語版をAmazonで予約",
    "read": "第1章を試し読み",
    "note": JA_NOTE,
    "alt": "『残りの10%』の表紙：川辺の灯台を岩の上から見つめる三人",
    "quote": "「ハイダン社では、仕事の<b>九割</b>をエージェントがこなす。<b>残りの一割</b>を引き受けているのが、タットだった。」",
    "leg1": "<b>90の点</b>：エージェントがこなす仕事",
    "leg2": "<b>10の点</b>：人間の手に残る仕事",
    "st_eb": "物語",
    "st_h": "AIエージェントを貸し出す会社と、その裏で働く十二人",
    "st1": "ハイダン社は、AIエージェントを月極めで貸し出している。顧客は一万社を超える「ひとり社長」の会社だ。毛糸の店、歯科医院、小さな縫製工房。社長はどこもひとりきりで、帳簿をつけ、客に声をかけ、真夜中のメッセージに返信するのはエージェントの一団である。",
    "st2": "そのプラットフォームの裏にいる生身の人間は、机二列を埋めるほどしかいない。彼らはエージェントの手に負えない案件を引き受ける。そして、ふと考えはじめる。機械が自分の仕事の九割をこなせるなら、残りの一割とはいったい何なのか。",
    "st3": "本書は、トヨタのカイゼンをはじめ、人がともに働くことをめぐる古くからの教えを、その書き手たちが思いもしなかった世界に置き直してみる。すると多くは、かえって確かさを増していく。",
    "ca_eb": "二列目の机から",
    "ca_h": "物語を最後までともに歩く三人",
    "r1": "主人公",
    "d1": "入社二年。仕事が速く、処理速度のランキングは四位。すべてが順調で、手帳に書くことがもう何も残っていない。",
    "r2": "創業期からの古株",
    "d2": "ハイダン社の最初期からいるひとり。口数は少ないが、三度目の報告をせざるをえなかった顧客を、ひとり残らず覚えている。",
    "r3": "チームリーダー",
    "d3": "働きはじめて二十年近く。人だけで回していたコールセンターの時代から、エージェントがほとんどをこなす今までを見てきた。いつも背の擦り切れた古い本を持ち歩き、会議テーブルのない場所でしか話をしたがらない。",
    "a1k": "各章のはじまり",
    "a1h": "ハイダン社の物語",
    "a1p": "難しい案件、ひとつの会議、川辺の午後。",
    "a2k": "物語のあいだに",
    "a2h": "理論コラム",
    "a2p": "物語の隣に、検証を重ねてきたマネジメント研究を置く。トヨタのカイゼンから心理的安全性まで。",
    "a3k": "各章のおわり",
    "a3h": "あなたへ",
    "a3p": "自分の仕事に持ち帰るための、いくつかの問い。",
    "toc_eb": "目次",
    "toc_h": "ひとりの人間から会社全体へ、全二十章",
    "ready": "いま読める",
    "soon": "近日公開",
    "p1": "第一部　まだ痛みを感じる人",
    "p2": "第二部　小さなチーム、大きな仕事",
    "p3": "第三部　会社が大きくなるとき",
    "p4": "第四部　残りの一割",
    "c": [
      "痛みの在りか",
      "新参者",
      "今日も昨日と同じ",
      "アイデアを売る",
      "難しい仕事は磁石になる",
      "自分と違う人",
      "正しい人をバスに乗せる",
      "すぐ褒め、本気で叱る",
      "やり方ではなく目標を渡す",
      "一番手の病",
      "職人",
      "石を探りながら川を渡る",
      "顧客はKPIではない",
      "大きくなることへの恐れ",
      "文化が隙間を埋める",
      "自動化の皮肉",
      "よく聴く人",
      "ほどよい恐れ",
      "最後列",
      "次の人"
    ],
    "th": [
      "カイゼン／小さな勝利",
      "ダブルループ学習／意図的な練習",
      "現状維持バイアス／成長マインドセット",
      "心理的安全性／ジョブ理論",
      "目標設定理論／Aに報いてBを望む愚",
      "多様性は能力に勝る／集団浅慮",
      "「まず誰を、それから何を」／集合知",
      "徹底した率直さ／公正な文化",
      "ミッション・コマンド／内発的動機づけ",
      "イノベーションのジレンマ",
      "職人／仕事への誇り",
      "情報が揃わないなかでの素早い決断",
      "グッドハートの法則",
      "組織の成長段階",
      "文化の三つのレベル",
      "自動化の皮肉",
      "人の変化を支える聴き方",
      "「パラノイアだけが生き残る」",
      "現場を歩くマネジメント",
      "内側から育つリーダー"
    ],
    "ending": "<b>エピローグ　意志あるところに。</b>川辺の、もうひとつの午後。けれど今度、古い本を手にしているのはタットだ。",
    "ex_eb": "試し読み・第1章",
    "ex_h": "痛みの在りか",
    "ex_sub": "三度目の報告",
    "ex_more": "日本語版は第{n}章まで公開中。続きは英語版とベトナム語の原書で読めます。",
    "full": "英語版をAmazonで予約",
    "sub": JA_FOLLOW,
    "f_eb": "物語を追いかける",
    "f_h": "一章ずつ、物語は進む",
    "f_p": "読み終えて、チュンさんに言い返したくなったり、タットの肩をもちたくなったりしたなら、この本は役目を果たしたことになる。",
    "o1k": "本",
    "o1v": "英語版 <i>The Last 10%</i> は2026年12月31日発売",
    "o1b": "英語版をAmazonで予約",
    "o2k": "一章ずつ、無料で",
    "o2v": NOTE_URL ? "新しい章の公開をnoteでお知らせします" : "日本語版はnoteで連載準備中。それまではLinkedInのニュースレター（英語・ベトナム語）で続きを追えます",
    "o2b": JA_FOLLOW,
    "ft": "ハイダン社および登場人物は、すべてフィクションです。",
    "excerpt": [
      "ハイダン社では、仕事の九割をエージェントがこなす。残りの一割を引き受けているのが、タン・タットだった。",
      "ハイダン社はAIエージェントの貸し出しを生業にしている。社名はベトナム語で「灯台」を意味する。顧客は、ここ数年で雨後の筍のように現れた新しいかたちの企業――社員がひとりしかいない会社だ。CEOはただひとり。その周りを、月極めで借りたエージェントの一団が固めている。経理エージェントが帳簿をつける。営業エージェントが客に声をかける。サポートエージェントが真夜中のメッセージに返信する。仕入れエージェントが毛糸を、布を、印刷用紙を発注する。そんな会社が一万社以上、ハイダン社のプラットフォームの上で昼も夜も動いている。一方、その裏側にいる生身の人間は、机二列をようやく埋めるほどしかいなかった。",
      "チャン・タン・タットは二列目の席、顧客オペレーションチームにいた。彼の仕事は、エージェントが自力で解決できなかった案件や、エージェントの対応にCEOが納得しなかった案件を引き取ることだ。そうした案件はどれも、短く乾いたチャイムとともに画面に現れる。スプーンでグラスの縁を軽く叩いたような音だ。この二年、それが一日におよそ百回。暗がりで横になっている夜にも、頭のどこかでその音が鳴り、そして消えることがあった。",
      "仕事は速かった。CEOとエージェントの長いやりとりも、数秒ざっと目を走らせるだけで、エージェントがどの一文で取り違えたのかがわかる。設定を直し、チケットを閉じ、次の案件を受ける。先週のランキングでは、処理速度で四位に彼の名前があった。一番ではない。けれど、彼について苦情を言った者も、これまでひとりもいなかった。",
      "すべては順調だった。そして、それこそが問題だったのだ。ただ、そのときの彼はまだ知らなかった。",
      "入社初日、彼は緊張のあまり、エージェントの推論を一行一行、推理小説でも読むように追ったものだ。エージェントが陥りがちな間違いのパターンを手帳三ページにびっしり書きつけ、営業エージェントがなぜ妙に堅苦しい口調で客に挨拶するのか、研修担当の女性に何度も尋ねた。いまその手帳は引き出しの中で眠り、表紙にはうっすらと埃が積もっている。もう開くこともない。書くことが、もう何もないのだ。"
    ]
  },
  // Bản tiếng Trung giản thể (ẩn, mới có chương 1). Tên sách 《剩下的百分之十》, nhân vật 胜必・力士・忠哥, công ty 海灯公司.
  "zh": {
    "cont": "继续阅读第1章",
    "other_lang": {"en":"将打开英文版（中文版翻译中）","vi":"将打开越南文原版（中文版翻译中）","es":"将打开西班牙文版","ja":"将打开日文版","zh":"将打开中文版"},
    "title": "剩下的百分之十",
    "eyebrow": "AI时代的管理小说",
    "h1": "剩下的<em>百分之十</em>",
    "q": "当AI智能体做完了九成的工作，人还剩下哪一成？",
    "buy": "在Amazon预订英文版",
    "read": "试读第1章",
    "note": ZH_NOTE,
    "alt": "《剩下的百分之十》封面：三个人站在岩石上，望向河边的灯塔",
    "quote": "“在海灯公司，智能体包揽了<b>百分之九十</b>的工作。<b>剩下的百分之十</b>，归胜必。”",
    "leg1": "<b>90个点</b>：智能体完成的工作",
    "leg2": "<b>10个点</b>：仍然属于人的部分",
    "st_eb": "故事",
    "st_h": "一家出租AI智能体的公司，和它背后的十二个人",
    "st1": "海灯公司按月出租AI智能体。它的客户是一万多家“一人公司”：毛线铺、牙科诊所、小小的制衣作坊。每家公司都只有一位老板，记账、招呼客人、半夜回消息的，是一整支租来的智能体团队。",
    "st2": "在这座平台背后，真人的数量刚好坐满两排办公桌。他们接手智能体解决不了的单子，也开始琢磨一个问题：如果机器能做完我九成的工作，剩下的那一成究竟是什么？",
    "st3": "这本书把关于人如何一起工作的老道理——从丰田的改善讲起——放进一个连它们的作者都未曾想象过的世界。结果多半是：这些道理反而更站得住了。",
    "ca_eb": "第二排办公桌",
    "ca_h": "陪你走完整本书的三个人",
    "r1": "主人公",
    "d1": "入职两年，干活快，处理速度排行榜第四。一切都好，好到他的笔记本里已经没什么可记的了。",
    "r2": "元老",
    "d2": "海灯公司最早的一批员工之一。话不多，却记得每一位不得不报修第三次的客户。",
    "r3": "组长",
    "d3": "工作了将近二十年，从全靠真人值守的呼叫中心，一直干到智能体的时代。总带着一本书脊翻白的旧书，只喜欢在没有会议桌的地方说话。",
    "a1k": "每章开篇",
    "a1h": "海灯公司的故事",
    "a1p": "一张棘手的工单，一场会，一个河边的下午。",
    "a2k": "穿插其间",
    "a2h": "理论角",
    "a2p": "在故事旁边，放上经过反复检验的管理学研究，从丰田的改善到心理安全感。",
    "a3k": "每章结尾",
    "a3h": "写给你",
    "a3p": "几个问题，带回你自己的工作中去。",
    "toc_eb": "目录",
    "toc_h": "二十章，从一个人到一整家公司",
    "ready": "现在可读",
    "soon": "即将推出",
    "p1": "第一部　还能感到痛的人",
    "p2": "第二部　小团队，大事情",
    "p3": "第三部　公司长大的时候",
    "p4": "第四部　剩下的百分之十",
    "c": [
      "痛处",
      "外乡人",
      "今天和昨天一样",
      "推销一个想法",
      "难事像磁铁",
      "和自己不一样的人",
      "让对的人上车",
      "及时表扬，真诚批评",
      "给目标，不给方法",
      "第一名的病",
      "手艺人",
      "摸着石头过河",
      "客户不是KPI",
      "变大的恐惧",
      "文化填补漏洞",
      "自动化的反讽",
      "善于倾听的人",
      "恰到好处的恐惧",
      "最后一排",
      "下一个人"
    ],
    "th": [
      "改善 · 小胜利",
      "双环学习 · 刻意练习",
      "现状偏差 · 成长型思维",
      "心理安全感 · 待办任务理论",
      "目标设定理论 · 奖励A却期待B",
      "多样性胜过能力 · 群体思维",
      "“先人后事” · 集体智慧",
      "绝对坦率 · 公正文化",
      "任务式指挥 · 内在动机",
      "创新者的窘境",
      "手艺人 · 以工作为荣",
      "信息不全时的快速决策",
      "古德哈特定律",
      "组织成长的阶段",
      "文化的三个层次",
      "自动化的反讽",
      "帮助人改变的倾听",
      "“只有偏执狂才能生存”",
      "走动式管理",
      "从内部成长起来的领导者"
    ],
    "ending": "<b>尾声　有志者，事竟成。</b>又一个河边的下午，只是这一次，捧着那本旧书的人是胜必。",
    "ex_eb": "试读 · 第1章",
    "ex_h": "痛处",
    "ex_sub": "第三次报修",
    "ex_more": "中文版已更新至第{n}章。后续章节可以先读英文版和越南文原版。",
    "full": "在Amazon预订英文版",
    "sub": ZH_FOLLOW,
    "f_eb": "追读故事",
    "f_h": "一章一章，故事往前走",
    "f_p": "如果读完一章，你想跟忠哥争上两句，或者想替胜必说句话，这本书就算尽到了它的本分。",
    "o1k": "书",
    "o1v": "英文版 <i>The Last 10%</i> 将于2026年12月31日出版",
    "o1b": "在Amazon预订英文版",
    "o2k": "逐章免费阅读",
    "o2v": WECHAT_URL ? "新章节发布后，会在微信公众号上通知你" : "中文版公众号正在筹备中。在此之前，可以通过LinkedIn通讯（英文、越南文）追读后续章节",
    "o2b": ZH_FOLLOW,
    "ft": "海灯公司及书中所有人物均为虚构。",
    "excerpt": [
      "在海灯公司，智能体包揽了百分之九十的工作。剩下的百分之十，归胜必。",
      "海灯公司做的是AI智能体租赁生意——“海灯”二字，在越南语里就是灯塔的意思。它的客户是近几年雨后春笋般冒出来的一种新型企业：一人公司。整家公司只有一位CEO，围在他身边的，是按月租来的一整支智能体团队。会计智能体记账，销售智能体招呼客人，客服智能体在半夜回复消息，采购智能体订毛线、订布料、订打印纸。一万多家这样的公司在海灯的平台上运转，昼夜不停。而在这座平台背后，真人的数量刚好坐满两排办公桌。",
      "陈胜必坐在第二排，属于客户运营组。他的工作是接手智能体自己解决不了的单子，或者CEO对智能体的处理不满意的单子。每一单弹上屏幕，都伴着一声短促、干脆的提示音，像勺子轻轻磕在杯沿上。两年来，每天大约一百声。有些夜里躺在黑暗中，他仍会听见它在脑子里某个地方响起，然后熄灭。",
      "他干活快。CEO和智能体之间一长串对话，他扫上几秒，就能看出智能体是在哪一句理解错了。调配置，关工单，接下一单。上周的排行榜上，他的速度排在第四。他算不上最出色的，但也从来没有人对他有过什么抱怨。",
      "一切都好。而问题恰恰就出在这里，只是那时他还不知道。",
      "刚上班的第一天，他紧张得把智能体的每一行推理都当侦探小说来读。他在本子上记满了三页智能体常犯的错误，还缠着带他的培训师姐问了又问：为什么销售智能体跟客人打招呼，总是一副客气得出奇的腔调？如今那个本子静静躺在抽屉里，封面落了薄薄一层灰。他不再翻开它了。他已经没什么可记的了。"
    ]
  }
}

export type Content = (typeof content)["vi"];
