// Nội dung trang theo ngôn ngữ. Sửa chữ ở đây, không cần đụng vào component.
export const AMAZON_URL = "https://a.co/d/0jbHvq34";
export const AUTHOR_URL = "https://www.linkedin.com/in/dangtrunganh";
export const LINKEDIN_URL = "https://www.linkedin.com/build-relation/newsletter-follow?entityUrn=7512726408108924930";

export const LANGS = ["vi", "en", "es"] as const;
export type Lang = (typeof LANGS)[number];

export const content = {
  "vi": {
    "cont": "Đọc tiếp chương 1",
    "other_lang": {"en":"Mở bản tiếng Anh","vi":"Mở bản tiếng Việt","es":"Mở bản tiếng Tây Ban Nha"},
    "title": "Mười phần trăm còn lại",
    "eyebrow": "Truyện quản trị · Mỗi tuần một chương",
    "h1": "Mười phần trăm <em>còn lại</em>",
    "q": "Khi agent làm gần hết mọi việc, con người lớn lên từ đâu?",
    "buy": "Đặt mua trên Amazon",
    "read": "Đọc thử chương 1",
    "note": "Mỗi tuần một chương mới. <a href=\"https://www.linkedin.com/build-relation/newsletter-follow?entityUrn=7512726408108924930\" target=\"_blank\" rel=\"noopener noreferrer\">Đăng ký bản tin trên LinkedIn</a>",
    "alt": "Bìa sách Mười phần trăm còn lại: ba người đứng trên mỏm đá nhìn về ngọn hải đăng bên bờ sông",
    "quote": "“Ở Hải Đăng, agent làm <b>chín mươi phần trăm</b> công việc. Thắng Tất lo <b>mười phần trăm còn lại</b>.”",
    "leg1": "<b>90 chấm</b> là phần việc agent làm",
    "leg2": "<b>10 chấm</b> là phần còn lại của con người",
    "st_eb": "Câu chuyện",
    "st_h": "Một công ty cho thuê AI agent, và vài chục con người phía sau",
    "st1": "Hải Đăng cho thuê AI agent theo tháng. Khách hàng của họ là hơn mười nghìn công ty chỉ có một CEO: một chủ tiệm len, một nha sĩ, một xưởng may nhỏ, mỗi người cùng một đội agent ghi sổ, chào khách, trả lời tin nhắn lúc nửa đêm.",
    "st2": "Phía sau nền tảng ấy, số người thật chỉ vừa đủ ngồi kín hai dãy bàn. Họ đón những ca agent không giải quyết được. Và họ bắt đầu tự hỏi: nếu máy làm được chín mươi phần trăm việc của mình, thì mười phần trăm còn lại là gì?",
    "st3": "Cuốn sách đặt những bài học cũ về cách con người làm việc với nhau vào một thế giới mà người viết ra chúng chưa từng hình dung. Phần lớn, chúng còn đúng hơn.",
    "ca_eb": "Những người ở dãy bàn thứ hai",
    "ca_h": "Ba người sẽ đi cùng bạn suốt cuốn sách",
    "r1": "Nhân vật chính",
    "d1": "Hai năm kinh nghiệm, làm việc nhanh, đứng thứ tư bảng xếp hạng tốc độ. Mọi thứ đều ổn, đến mức anh không còn gì để ghi vào cuốn sổ.",
    "r2": "Người của những ngày đầu",
    "d2": "Một trong những người đầu tiên của Hải Đăng. Ít nói, nhưng nhớ từng khách hàng đã phải báo đến lần thứ ba.",
    "r3": "Trưởng nhóm",
    "d3": "Gần hai mươi năm đi làm, từ thời tổng đài toàn người trực đến thời agent làm gần hết. Luôn mang theo một cuốn sách cũ sờn gáy, và chỉ thích nói chuyện ở những chỗ không có bàn họp.",
    "a1k": "Mở đầu mỗi chương",
    "a1h": "Một câu chuyện ở Hải Đăng",
    "a1p": "Một ca khó, một cuộc họp, một buổi chiều bên bờ sông.",
    "a2k": "Xen giữa",
    "a2h": "Góc lý thuyết",
    "a2p": "Câu chuyện đặt cạnh một nghiên cứu quản trị đã được kiểm chứng, từ Kaizen của Toyota đến an toàn tâm lý.",
    "a3k": "Cuối chương",
    "a3h": "Dành cho bạn",
    "a3p": "Vài câu hỏi để mang về công việc của chính mình.",
    "toc_eb": "Mục lục",
    "toc_h": "Mười bốn chương, từ một con người đến cả công ty",
    "ready": "Đọc được ngay",
    "soon": "Sắp ra mắt",
    "p1": "Phần I · Người còn thấy đau",
    "p2": "Phần II · Đội nhỏ, việc lớn",
    "p3": "Phần III · Khi công ty lớn lên",
    "c": [
      "Chỗ đau",
      "Người nhập cư",
      "Ngày hôm nay giống hôm qua",
      "Bán một ý tưởng",
      "Việc khó như nam châm",
      "Người khác mình",
      "Đúng người trên xe",
      "Khen ngay, chê thật",
      "Giao mục tiêu, không giao cách làm",
      "Bệnh của người số một",
      "Khách hàng không phải KPI",
      "Văn hóa lấp lỗ hổng",
      "Sợ hãi vừa đủ",
      "Người kế tiếp"
    ],
    "th": [
      "Kaizen · thắng lợi nhỏ",
      "Học vòng kép · luyện tập có chủ đích",
      "Thiên kiến hiện trạng · tư duy phát triển",
      "An toàn tâm lý · Jobs to Be Done",
      "Thuyết đặt mục tiêu",
      "Sức mạnh của sự khác biệt",
      "“Ai trước, việc sau”",
      "Radical Candor",
      "Chỉ huy theo sứ mệnh",
      "Thế lưỡng nan của nhà đổi mới",
      "Định luật Goodhart",
      "Ba tầng văn hóa",
      "“Chỉ kẻ đa nghi mới sống sót”",
      "Lãnh đạo trưởng thành từ bên trong"
    ],
    "ending": "<b>Lời kết · Nơi nào có ý chí.</b> Một buổi chiều nữa bên bờ sông, nhưng lần này người cầm cuốn sách cũ là Thắng Tất.",
    "ex_eb": "Đọc thử · Chương 1",
    "ex_h": "Chỗ đau",
    "ex_sub": "Lần báo thứ ba",
    "ex_more": "Chương 1 đến {n} đã ra trên LinkedIn. Sách đã có trên Amazon.",
    "full": "Đặt mua sách",
    "sub": "Đăng ký trên LinkedIn",
    "f_eb": "Theo dõi câu chuyện",
    "f_h": "Mỗi tuần, một chương mới",
    "f_p": "Đọc xong chương nào mà bạn muốn cãi lại Trung, hay bênh vực Thắng Tất, thì cuốn sách đã làm được việc của nó.",
    "o1k": "Sách",
    "o1v": "<i>The Last 10%</i> đã có trên Amazon",
    "o1b": "Đặt mua trên Amazon",
    "o2k": "Từng chương, miễn phí",
    "o2v": "Nhận chương mới mỗi tuần qua bản tin <i>Mười phần trăm còn lại</i>",
    "o2b": "Đăng ký trên LinkedIn",
    "ft": "Hải Đăng và các nhân vật trong sách đều là hư cấu.",
    "excerpt": [
      "Ở Hải Đăng, agent làm chín mươi phần trăm công việc. Thắng Tất lo mười phần trăm còn lại.",
      "Hải Đăng cho thuê AI agent. Khách hàng của họ là một kiểu doanh nghiệp mới mọc lên vài năm gần đây, nhiều như nấm sau mưa: công ty chỉ có một người. Một CEO duy nhất, và quanh người ấy là cả một đội agent thuê theo tháng. Agent kế toán ghi sổ. Agent bán hàng chào khách. Agent chăm sóc trả lời tin nhắn lúc nửa đêm. Agent nhập hàng đặt len, đặt vải, đặt giấy in. Hơn mười nghìn công ty như thế đang chạy trên nền tảng của Hải Đăng, ngày cũng như đêm. Còn phía sau nền tảng ấy, số người thật chỉ vừa đủ ngồi kín hai dãy bàn.",
      "Trần Thắng Tất ngồi ở dãy thứ hai, trong nhóm vận hành khách hàng. Việc của anh là đón những ca agent không tự giải quyết được, hoặc những ca CEO không hài lòng với cách agent đã giải quyết. Mỗi ca như vậy hiện lên màn hình kèm một tiếng chuông ngắn, khô, giống tiếng thìa gõ vào thành cốc. Hai năm nay, mỗi ngày chừng một trăm tiếng như thế. Có những đêm nằm trong bóng tối, anh vẫn nghe nó vang lên đâu đó trong đầu, rồi tắt.",
      "Anh làm việc nhanh. Một đoạn hội thoại dài giữa CEO và agent, anh lướt qua trong vài giây là thấy ngay agent đã hiểu sai ở câu nào. Chỉnh cấu hình, đóng phiếu, nhận ca tiếp theo. Bảng xếp hạng tuần trước để tên anh ở vị trí thứ tư về tốc độ. Anh không phải người giỏi nhất, nhưng cũng chưa từng có ai phàn nàn gì về anh.",
      "Mọi thứ đều ổn. Và chính điều đó mới là vấn đề, chỉ là lúc ấy anh chưa biết.",
      "Ngày đầu đi làm, anh hồi hộp đến mức đọc từng dòng suy luận của agent như đọc một cuốn truyện trinh thám. Anh ghi kín ba trang sổ về những kiểu lỗi agent hay mắc, hỏi đi hỏi lại chị huấn luyện vì sao agent bán hàng cứ chào khách bằng một giọng trang trọng đến lạ. Bây giờ cuốn sổ nằm im trong ngăn kéo, bìa phủ một lớp bụi mỏng. Anh không còn mở nó ra nữa. Anh không còn gì để ghi."
    ]
  },
  "en": {
    "cont": "Keep reading Chapter 1",
    "other_lang": {"en":"Opens in English","vi":"Opens in Vietnamese (not yet translated)","es":"Opens in Spanish"},
    "title": "The Last 10%",
    "eyebrow": "A management novel · One chapter a week",
    "h1": "The Last <em>10%</em>",
    "q": "When AI agents do almost everything, where do people still grow?",
    "buy": "Buy on Amazon",
    "read": "Read Chapter 1",
    "note": "New chapters every week. <a href=\"https://www.linkedin.com/build-relation/newsletter-follow?entityUrn=7512726408108924930\" target=\"_blank\" rel=\"noopener noreferrer\">Subscribe to the newsletter on LinkedIn</a>",
    "alt": "Cover of The Last 10%: three people on a rocky ledge looking toward a lighthouse by the river",
    "quote": "“At Hải Đăng, agents did <b>ninety percent</b> of the work. Thắng Tất handled <b>the last ten</b>.”",
    "leg1": "<b>90 dots</b>: the work agents do",
    "leg2": "<b>10 dots</b>: the part that is still human",
    "st_eb": "The story",
    "st_h": "A company that rents out AI agents, and the few dozen people behind it",
    "st1": "Hải Đăng, Vietnamese for “lighthouse”, rents out AI agents by the month. Its customers are more than ten thousand companies run by a single CEO: a yarn shop owner, a dentist, a small garment workshop, each with a team of agents that keep the books, greet customers and answer messages at midnight.",
    "st2": "Behind the platform, the actual humans barely fill two rows of desks. They take the cases the agents cannot solve. And they have started to wonder: if a machine can do ninety percent of my job, what is the other ten percent?",
    "st3": "The book places old lessons about how people work together in a world their authors never imagined. Mostly, they hold even better.",
    "ca_eb": "The second row of desks",
    "ca_h": "Three people who walk with you through the whole book",
    "r1": "The protagonist",
    "d1": "Two years in, fast at his job, fourth on the speed leaderboard. Everything is fine, so fine that he has nothing left to write in his notebook.",
    "r2": "One of the first hires",
    "d2": "Among the first people at Hải Đăng. Quiet, but he remembers every customer who had to report something a third time.",
    "r3": "The team lead",
    "d3": "Almost twenty years of work, from call centres staffed entirely by people to the age of agents. Always carries a worn old book, and only likes to talk in places with no meeting tables.",
    "a1k": "Each chapter opens with",
    "a1h": "A story at Hải Đăng",
    "a1p": "A hard case, a meeting, an afternoon by the river.",
    "a2k": "Woven through",
    "a2h": "Theory corners",
    "a2p": "The story set beside well-tested management research, from Toyota’s Kaizen to psychological safety.",
    "a3k": "Each chapter ends with",
    "a3h": "For you",
    "a3p": "A few questions to take back to your own work.",
    "toc_eb": "Contents",
    "toc_h": "Fourteen chapters, from one person to a whole company",
    "ready": "Read now",
    "soon": "Coming soon",
    "p1": "Part I · Those Who Still Feel It",
    "p2": "Part II · Small Team, Big Work",
    "p3": "Part III · When the Company Grows Up",
    "c": [
      "Where It Hurts",
      "The Immigrant",
      "Today, Like Yesterday",
      "Selling an Idea",
      "Hard Problems Are Magnets",
      "People Unlike Us",
      "The Right People on the Bus",
      "Praise Now, Criticize Honestly",
      "Give Goals, Not Methods",
      "The Number-One Disease",
      "Customers Are Not KPIs",
      "Culture Fills the Gaps",
      "Just Enough Fear",
      "The Next One"
    ],
    "th": [
      "Kaizen · small wins",
      "Double-loop learning · deliberate practice",
      "Status quo bias · growth mindset",
      "Psychological safety · Jobs to Be Done",
      "Goal-setting theory",
      "The power of diversity",
      "“First who, then what”",
      "Radical Candor",
      "Mission command",
      "The innovator’s dilemma",
      "Goodhart’s law",
      "Three levels of culture",
      "“Only the paranoid survive”",
      "Home-grown leadership"
    ],
    "ending": "<b>Epilogue · Where There Is a Will.</b> One more afternoon by the river, but this time it is Thắng Tất holding the old book.",
    "ex_eb": "Sample · Chapter 1",
    "ex_h": "Where It Hurts",
    "ex_sub": "The Third Report",
    "ex_more": "Chapters 1 to {n} are out. The book is available on Amazon.",
    "full": "Get the book",
    "sub": "Subscribe on LinkedIn",
    "f_eb": "Follow the story",
    "f_h": "A new chapter every week",
    "f_p": "If you finish a chapter wanting to argue with Trung, or to stand up for Thắng Tất, the book has done its job.",
    "o1k": "The book",
    "o1v": "<i>The Last 10%</i> is available now on Amazon",
    "o1b": "Buy on Amazon",
    "o2k": "Chapter by chapter, free",
    "o2v": "Get each new chapter through the LinkedIn newsletter",
    "o2b": "Subscribe on LinkedIn",
    "ft": "Hải Đăng and all characters in the book are fictional.",
    "excerpt": [
      "At Hải Đăng, agents did ninety percent of the work. Thắng Tất handled the last ten.",
      "Hải Đăng, Vietnamese for “lighthouse”, rented out AI agents. Its customers were a new kind of business that had sprung up over the past few years: the one-person company. A single CEO, backed by a team of agents rented by the month. An accounting agent, a sales agent, a customer care agent, a purchasing agent. More than ten thousand companies like that ran on Hải Đăng’s platform. Behind the platform, the actual humans barely filled two rows of desks.",
      "Trần Thắng Tất sat in the second row, on the customer operations team. His job was to handle the cases agents couldn’t resolve on their own, or the ones where a CEO didn’t like how an agent had resolved them. Each case arrived on his screen with a short chime. Two years, about a hundred chimes a day. So many that some nights, lying in bed, he could still hear them.",
      "Thắng Tất was fast. He could read a conversation between a CEO and an agent in seconds, spot exactly where the agent had misunderstood, fix the configuration and close the ticket. Last week’s leaderboard ranked him fourth for handling time. He wasn’t the best, but nobody ever complained about him either.",
      "And that was the problem. Everything was fine.",
      "On his first day, Thắng Tất had been so nervous he read every line of an agent’s reasoning like a detective novel. He filled three pages of a notebook with the kinds of mistakes agents tended to make, and kept asking the trainer why the sales agent greeted customers so stiffly. Now the notebook sat in a drawer, its cover gathering dust. He didn’t need it anymore."
    ]
  },
  "es": {
    "cont": "Seguir leyendo el capítulo 1",
    "other_lang": {"en":"Se abre en inglés","vi":"Se abre en vietnamita (aún sin traducir)","es":"Se abre en español"},
    "title": "El último 10 %",
    "eyebrow": "Novela de management · Un capítulo por semana",
    "h1": "El último <em>10 %</em>",
    "q": "Cuando los agentes de IA hacen casi todo, ¿dónde siguen creciendo las personas?",
    "buy": "Comprar en Amazon",
    "read": "Leer el capítulo 1",
    "note": "Un capítulo nuevo cada semana. <a href=\"https://www.linkedin.com/build-relation/newsletter-follow?entityUrn=7512726408108924930\" target=\"_blank\" rel=\"noopener noreferrer\">Suscríbete al boletín en LinkedIn</a>",
    "alt": "Portada de The Last 10%: tres personas sobre una roca miran hacia un faro junto al río",
    "quote": "“En Hải Đăng, los agentes hacían <b>el noventa por ciento</b> del trabajo. Thắng Tất se ocupaba <b>del diez restante</b>.”",
    "leg1": "<b>90 puntos</b>: el trabajo que hacen los agentes",
    "leg2": "<b>10 puntos</b>: la parte que sigue siendo humana",
    "st_eb": "La historia",
    "st_h": "Una empresa que alquila agentes de IA, y las pocas decenas de personas que hay detrás",
    "st1": "Hải Đăng, que en vietnamita significa “faro”, alquila agentes de IA por meses. Sus clientes son más de diez mil empresas dirigidas por un solo CEO: una tienda de lanas, una clínica dental, un pequeño taller de confección, cada uno con un equipo de agentes que lleva la contabilidad, atiende a los clientes y responde mensajes a medianoche.",
    "st2": "Detrás de la plataforma, las personas de carne y hueso apenas llenan dos filas de escritorios. Se encargan de los casos que los agentes no saben resolver. Y han empezado a preguntarse: si una máquina puede hacer el noventa por ciento de mi trabajo, ¿qué es el diez por ciento restante?",
    "st3": "El libro lleva viejas lecciones sobre cómo trabajamos juntos a un mundo que sus autores nunca imaginaron. Casi siempre, resultan aún más ciertas.",
    "ca_eb": "La segunda fila de escritorios",
    "ca_h": "Tres personas que te acompañarán durante todo el libro",
    "r1": "El protagonista",
    "d1": "Dos años en la empresa, rápido, cuarto en la clasificación de velocidad. Todo va bien, tan bien que ya no le queda nada que anotar en su cuaderno.",
    "r2": "De los primeros",
    "d2": "Una de las primeras personas de Hải Đăng. Habla poco, pero recuerda a cada cliente que tuvo que avisar por tercera vez.",
    "r3": "El jefe de equipo",
    "d3": "Casi veinte años de oficio, desde las centralitas atendidas solo por personas hasta la era de los agentes. Siempre lleva un libro viejo con el lomo gastado, y solo le gusta conversar donde no hay mesas de reuniones.",
    "a1k": "Cada capítulo empieza con",
    "a1h": "Una historia en Hải Đăng",
    "a1p": "Un caso difícil, una reunión, una tarde junto al río.",
    "a2k": "Entremedias",
    "a2h": "Rincones de teoría",
    "a2p": "La historia junto a una investigación de gestión contrastada, del Kaizen de Toyota a la seguridad psicológica.",
    "a3k": "Cada capítulo termina con",
    "a3h": "Para ti",
    "a3p": "Unas preguntas para llevarte a tu propio trabajo.",
    "toc_eb": "Índice",
    "toc_h": "Catorce capítulos, de una persona a toda una empresa",
    "ready": "Disponible",
    "soon": "Próximamente",
    "p1": "Parte I · Quienes aún sienten el dolor",
    "p2": "Parte II · Equipo pequeño, gran trabajo",
    "p3": "Parte III · Cuando la empresa crece",
    "c": [
      "Donde duele",
      "El inmigrante",
      "Hoy, igual que ayer",
      "Vender una idea",
      "Los retos difíciles son imanes",
      "Gente distinta a nosotros",
      "Las personas adecuadas en el autobús",
      "Elogiar al momento, criticar con sinceridad",
      "Dar objetivos, no métodos",
      "La enfermedad del número uno",
      "Los clientes no son KPI",
      "La cultura llena los huecos",
      "El miedo justo",
      "El siguiente"
    ],
    "th": [
      "Kaizen · pequeñas victorias",
      "Aprendizaje de doble bucle · práctica deliberada",
      "Sesgo del statu quo · mentalidad de crecimiento",
      "Seguridad psicológica · Jobs to Be Done",
      "Teoría del establecimiento de metas",
      "El poder de la diversidad",
      "“Primero quién, después qué”",
      "Radical Candor",
      "Mando por misión",
      "El dilema del innovador",
      "Ley de Goodhart",
      "Los tres niveles de la cultura",
      "“Solo los paranoicos sobreviven”",
      "Liderazgo formado desde dentro"
    ],
    "ending": "<b>Epílogo · Donde hay voluntad.</b> Otra tarde junto al río, pero esta vez quien sostiene el viejo libro es Thắng Tất.",
    "ex_eb": "Adelanto · Capítulo 1",
    "ex_h": "Donde duele",
    "ex_sub": "El tercer aviso",
    "ex_more": "Ya se publicaron los capítulos 1 a {n}. El libro está disponible en Amazon.",
    "full": "Comprar el libro",
    "sub": "Suscribirse en LinkedIn",
    "f_eb": "Sigue la historia",
    "f_h": "Un capítulo nuevo cada semana",
    "f_p": "Si terminas un capítulo con ganas de discutir con Trung, o de defender a Thắng Tất, el libro ha cumplido su función.",
    "o1k": "El libro",
    "o1v": "<i>The Last 10%</i> ya está disponible en Amazon",
    "o1b": "Comprar en Amazon",
    "o2k": "Capítulo a capítulo, gratis",
    "o2v": "Recibe cada capítulo nuevo en el boletín de LinkedIn",
    "o2b": "Suscribirse en LinkedIn",
    "ft": "Hải Đăng y todos los personajes del libro son ficticios.",
    "excerpt": [
      "En Hải Đăng, que en vietnamita significa ‘faro’, los agentes hacían el noventa por ciento del trabajo. Thắng Tất se ocupaba del diez por ciento restante.",
      "Hải Đăng alquilaba agentes de IA. Sus clientes eran un tipo nuevo de empresa que en los últimos años había brotado como hongos después de la lluvia: la empresa de una sola persona. Un único CEO y, a su alrededor, todo un equipo de agentes alquilados por mes. El agente contable llevaba los libros. El agente de ventas atendía a los clientes. El agente de atención respondía mensajes a medianoche. El agente de compras pedía lana, tela, papel para imprimir. Más de diez mil empresas así funcionaban sobre la plataforma de Hải Đăng, de día y de noche. Detrás de esa plataforma, las personas de carne y hueso apenas alcanzaban para llenar dos filas de escritorios.",
      "Trần Thắng Tất se sentaba en la segunda fila, en el equipo de operaciones con clientes. Su trabajo era recibir los casos que los agentes no lograban resolver por sí mismos, o aquellos en los que el CEO no estaba conforme con cómo el agente los había resuelto. Cada caso aparecía en su pantalla acompañado de un timbre corto y seco, como una cucharita golpeando el borde de un vaso. Desde hacía dos años, unos cien timbres así cada día. Había noches en que, acostado en la oscuridad, todavía lo oía sonar en algún lugar de su cabeza, y luego apagarse.",
      "Trabajaba rápido. Una conversación larga entre un CEO y un agente le bastaba recorrerla en unos segundos para ver en qué frase el agente había entendido mal. Ajustar la configuración, cerrar el ticket, tomar el siguiente caso. La tabla de la semana anterior ponía su nombre en el cuarto lugar en velocidad. No era el mejor, pero tampoco nadie se había quejado nunca de él.",
      "Todo estaba bien. Y ese era justamente el problema, solo que en ese momento él todavía no lo sabía.",
      "Su primer día de trabajo estaba tan nervioso que leía cada línea del razonamiento de los agentes como si fuera una novela policial. Llenó tres páginas de un cuaderno con los tipos de errores que solían cometer los agentes, y le preguntaba una y otra vez a la instructora por qué el agente de ventas saludaba a los clientes con un tono tan extrañamente solemne. Ahora el cuaderno dormía en un cajón, con la tapa cubierta por una fina capa de polvo. Ya no lo abría. Ya no tenía nada que anotar."
]
  }
}

export type Content = (typeof content)["vi"];
