// Chữ cho các phần tương tác: đếm ngược, thanh mời đăng ký, câu trích, chương kế tiếp.
import type { Lang } from "./content";

/** Lịch đủ chương mặc định (khi không có chương đang mở dần): 0:00 thứ Hai (1), giờ Việt Nam */
export const RELEASE = { weekday: 1, hour: 0, minute: 0, utcOffset: 7 };


export const UI = {
  vi: {
    nextK: "Chương tiếp theo",
    readN: (n: number) => `Đọc chương ${n}`,
    weekK: "Tuần sau",
    outIn: "Đủ chương sau",
    units: ["ngày", "giờ", "phút", "giây"],
    when: "0:00 thứ Hai (giờ Việt Nam)",
    outNow: "Chương mới đã lên LinkedIn",
    quotesK: "Câu đáng nhớ",
    share: "Chia sẻ lên LinkedIn",
    copied: "Câu trích đã được điền vào bài đăng (và chép sẵn, nếu cần dán lại).",
    barText: "Thích chương này? Mỗi tuần một chương mới.",
    close: "Đóng",
    read: "Đã đọc",
    chapter: "Chương",
    thisWeek: "Tuần này",
    thisWeekAlt: "Tuần này",
    subs: "người đăng ký bản tin",
    writing: "Đang lên dần",
    live: "Đang mở thêm phần mới",
    idle: (t: string) => `Phần tiếp theo mở lúc ${t}`,
    today: "hôm nay",
    tomorrow: "ngày mai",
    tz: "",
    readDraft: "Đọc phần đã mở",
    draftNote: "Chương đang được đăng dần. Đủ chương vào thứ Hai.",
    reachedEnd: "Bạn đã đọc tới phần mới nhất.",
    words: (w: number, t: number) => `${w.toLocaleString("vi-VN")} / ${t.toLocaleString("vi-VN")} chữ`,
    legendNative: "Đọc được ngay",
    legendAlt: "",
    altNote: (_l: string) => "",
    weekAlt: "Tuần sau",
    status: (_native: number, _released: number) => "",
  },
  en: {
    nextK: "Next chapter",
    readN: (n: number) => `Read Chapter ${n}`,
    weekK: "Next week",
    outIn: "Full chapter in",
    units: ["d", "h", "m", "s"],
    when: "Monday, 12:00 a.m. Vietnam time",
    outNow: "The new chapter is out on LinkedIn",
    quotesK: "Lines worth keeping",
    share: "Share on LinkedIn",
    copied: "The quote is in your post (and copied, in case you need to paste it).",
    barText: "Enjoying this? A new chapter every week.",
    close: "Close",
    read: "Read",
    chapter: "Chapter",
    thisWeek: "This week",
    thisWeekAlt: "This week · Vietnamese original",
    subs: "newsletter subscribers",
    writing: "Releasing",
    live: "New pages are opening now",
    idle: (t: string) => `Next pages open at ${t}`,
    today: "today",
    tomorrow: "tomorrow",
    tz: " (Vietnam time)",
    readDraft: "Read what’s out so far",
    draftNote: "This chapter is being published bit by bit, in Vietnamese. The full chapter is out on Monday.",
    reachedEnd: "You’ve reached the newest page.",
    words: (w: number, t: number) => `${w.toLocaleString("en-US")} / ${t.toLocaleString("en-US")} words`,
    legendNative: "Read in English",
    legendAlt: "Vietnamese original · translation on the way",
    altNote: (_l: string) => "Vietnamese original · English translation on the way",
    weekAlt: "Next week · Vietnamese original",
    status: (native: number, released: number) =>
      `The Vietnamese edition runs ahead: ${released} chapters out in Vietnamese, ${native} in English.`,
  },
  es: {
    nextK: "Siguiente capítulo",
    readN: (n: number) => `Leer el capítulo ${n}`,
    weekK: "La próxima semana",
    outIn: "Capítulo completo en",
    units: ["d", "h", "min", "s"],
    when: "Lunes, 0:00 (hora de Vietnam)",
    outNow: "El nuevo capítulo ya está en LinkedIn",
    quotesK: "Frases para recordar",
    share: "Compartir en LinkedIn",
    copied: "La frase ya está en tu publicación (y copiada, por si hace falta pegarla).",
    barText: "¿Te gusta? Un capítulo nuevo cada semana.",
    close: "Cerrar",
    read: "Leído",
    chapter: "Capítulo",
    thisWeek: "Esta semana",
    thisWeekAlt: "Esta semana · original en vietnamita",
    subs: "suscriptores al boletín",
    writing: "En publicación",
    live: "Se están abriendo páginas nuevas",
    idle: (t: string) => `Las siguientes páginas se abren a las ${t}`,
    today: "hoy",
    tomorrow: "mañana",
    tz: " (hora de Vietnam)",
    readDraft: "Leer lo publicado",
    draftNote: "Este capítulo se publica poco a poco, en vietnamita. El capítulo completo sale el lunes.",
    reachedEnd: "Has llegado a la página más reciente.",
    words: (w: number, t: number) => `${w.toLocaleString("es-ES")} / ${t.toLocaleString("es-ES")} palabras`,
    legendNative: "Leer en español",
    legendAlt: "Aún sin traducir al español",
    altNote: (l: string) =>
      l === "en" ? "Disponible en inglés · traducción al español en curso" : "Solo en vietnamita · traducción en curso",
    weekAlt: "Próxima semana · original en vietnamita",
    status: (native: number, released: number) =>
      `La edición en vietnamita va por delante: ${released} capítulos en vietnamita, ${native} en español.`,
  },
  ja: {
    nextK: "次の章",
    readN: (n: number) => `第${n}章を読む`,
    weekK: "次の章",
    outIn: "原書の次の章まで",
    units: ["日", "時間", "分", "秒"],
    when: "原書は毎週月曜0時（ベトナム時間）に公開",
    outNow: "新しい章が公開されました",
    quotesK: "心に残る一文",
    share: "Xでシェア",
    copied: "引用をXの投稿画面に入れました。",
    barText: "続きが気になったら、こちらから。",
    close: "閉じる",
    read: "読了",
    chapter: "章",
    thisWeek: "今週",
    thisWeekAlt: "今週・ベトナム語の原書",
    subs: "人が購読中",
    writing: "公開中",
    live: "新しいページを公開しています",
    idle: (t: string) => `次のページは${t}に公開`,
    today: "今日",
    tomorrow: "明日",
    tz: "（ベトナム時間）",
    readDraft: "公開済みの部分を読む",
    draftNote: "この章はベトナム語で少しずつ公開しています。全文は月曜日に公開されます。",
    reachedEnd: "最新のページまで読みました。",
    words: (w: number, t: number) => `${w.toLocaleString("ja-JP")} / ${t.toLocaleString("ja-JP")} 語`,
    legendNative: "日本語で読める",
    legendAlt: "日本語訳は準備中",
    altNote: (l: string) => (l === "en" ? "英語版で公開中・日本語訳は準備中" : "ベトナム語の原書のみ・日本語訳は準備中"),
    weekAlt: "次の章・ベトナム語の原書",
    status: (native: number, released: number) =>
      `ベトナム語の原書が先行しています。原書は第${released}章まで、日本語版は第${native}章まで公開中。`,
  },
  zh: {
    nextK: "下一章",
    readN: (n: number) => `阅读第${n}章`,
    weekK: "下一章",
    outIn: "距原版下一章更新",
    units: ["天", "小时", "分", "秒"],
    when: "原版每周一0点（越南时间）更新",
    outNow: "新章节已发布",
    quotesK: "值得记下的话",
    share: "分享到微博",
    copied: "已复制金句和链接，可直接粘贴到微信。",
    barText: "想看后面的故事？从这里关注。",
    close: "关闭",
    read: "已读",
    chapter: "章",
    thisWeek: "本周",
    thisWeekAlt: "本周 · 越南文原版",
    subs: "人已订阅",
    writing: "连载中",
    live: "正在放出新的内容",
    idle: (t: string) => `下一部分将于${t}放出`,
    today: "今天",
    tomorrow: "明天",
    tz: "（越南时间）",
    readDraft: "阅读已放出的部分",
    draftNote: "本章正在以越南文逐步连载，完整章节将于周一发布。",
    reachedEnd: "你已读到最新的部分。",
    words: (w: number, t: number) => `${w.toLocaleString("zh-CN")} / ${t.toLocaleString("zh-CN")} 字`,
    legendNative: "可读中文版",
    legendAlt: "中文版翻译中",
    altNote: (l: string) => (l === "en" ? "已有英文版 · 中文版翻译中" : "仅有越南文原版 · 中文版翻译中"),
    weekAlt: "下一章 · 越南文原版",
    status: (native: number, released: number) =>
      `越南文原版更新在前：原版已更新至第${released}章，中文版已更新至第${native}章。`,
  },
} satisfies Record<Lang, unknown>;

/** 「第3章」: số chương kiểu tiếng Nhật (tiếng Trung viết y hệt: 第3章) */
export const jaCh = (n: number) => `第${n}章`;

/** Bản chữ Hán (ja, zh): số chương viết 第N章, tên chương cách bằng khoảng trắng toàn góc, không có chữ nghiêng */
export const isCJK = (lang: Lang): lang is "ja" | "zh" => lang === "ja" || lang === "zh";
