// Chữ cho các phần tương tác: đếm ngược, thanh mời đăng ký, câu trích, chương kế tiếp.
import type { Lang } from "./content";

/** Lịch đủ chương mặc định (khi không có chương đang mở dần): 0:00 thứ Hai (1), giờ Việt Nam */
export const RELEASE = { weekday: 1, hour: 0, minute: 0, utcOffset: 7 };


export const UI = {
  vi: {
    nextK: "Chương tiếp theo",
    readN: (n: number) => `Đọc chương ${n}`,
    weekK: "Tuần sau",
    outIn: "Đủ chương sau",
    units: ["ngày", "giờ", "phút", "giây"],
    when: "0:00 thứ Hai (giờ Việt Nam)",
    outNow: "Chương mới đã lên LinkedIn",
    quotesK: "Câu đáng nhớ",
    share: "Chia sẻ lên LinkedIn",
    copied: "Câu trích đã được điền vào bài đăng (và chép sẵn, nếu cần dán lại).",
    barText: "Thích chương này? Mỗi tuần một chương mới.",
    close: "Đóng",
    read: "Đã đọc",
    chapter: "Chương",
    thisWeek: "Tuần này",
    thisWeekAlt: "Tuần này",
    subs: "người đăng ký bản tin",
    writing: "Đang lên dần",
    live: "Đang mở thêm phần mới",
    idle: (t: string) => `Phần tiếp theo mở lúc ${t}`,
    today: "hôm nay",
    tomorrow: "ngày mai",
    tz: "",
    readDraft: "Đọc phần đã mở",
    draftNote: "Chương đang được đăng dần. Đủ chương vào thứ Hai.",
    reachedEnd: "Bạn đã đọc tới phần mới nhất.",
    words: (w: number, t: number) => `${w.toLocaleString("vi-VN")} / ${t.toLocaleString("vi-VN")} chữ`,
    legendNative: "Đọc được ngay",
    legendAlt: "",
    altNote: (_l: string) => "",
    weekAlt: "Tuần sau",
    status: (_native: number, _released: number) => "",
  },
  en: {
    nextK: "Next chapter",
    readN: (n: number) => `Read Chapter ${n}`,
    weekK: "Next week",
    outIn: "Full chapter in",
    units: ["d", "h", "m", "s"],
    when: "Monday, 12:00 a.m. Vietnam time",
    outNow: "The new chapter is out on LinkedIn",
    quotesK: "Lines worth keeping",
    share: "Share on LinkedIn",
    copied: "The quote is in your post (and copied, in case you need to paste it).",
    barText: "Enjoying this? A new chapter every week.",
    close: "Close",
    read: "Read",
    chapter: "Chapter",
    thisWeek: "This week",
    thisWeekAlt: "This week · Vietnamese original",
    subs: "newsletter subscribers",
    writing: "Releasing",
    live: "New pages are opening now",
    idle: (t: string) => `Next pages open at ${t}`,
    today: "today",
    tomorrow: "tomorrow",
    tz: " (Vietnam time)",
    readDraft: "Read what’s out so far",
    draftNote: "This chapter is being published bit by bit, in Vietnamese. The full chapter is out on Monday.",
    reachedEnd: "You’ve reached the newest page.",
    words: (w: number, t: number) => `${w.toLocaleString("en-US")} / ${t.toLocaleString("en-US")} words`,
    legendNative: "Read in English",
    legendAlt: "Vietnamese original · translation on the way",
    altNote: (_l: string) => "Vietnamese original · English translation on the way",
    weekAlt: "Next week · Vietnamese original",
    status: (native: number, released: number) =>
      `The Vietnamese edition runs ahead: ${released} chapters out in Vietnamese, ${native} in English.`,
  },
  es: {
    nextK: "Siguiente capítulo",
    readN: (n: number) => `Leer el capítulo ${n}`,
    weekK: "La próxima semana",
    outIn: "Capítulo completo en",
    units: ["d", "h", "min", "s"],
    when: "Lunes, 0:00 (hora de Vietnam)",
    outNow: "El nuevo capítulo ya está en LinkedIn",
    quotesK: "Frases para recordar",
    share: "Compartir en LinkedIn",
    copied: "La frase ya está en tu publicación (y copiada, por si hace falta pegarla).",
    barText: "¿Te gusta? Un capítulo nuevo cada semana.",
    close: "Cerrar",
    read: "Leído",
    chapter: "Capítulo",
    thisWeek: "Esta semana",
    thisWeekAlt: "Esta semana · original en vietnamita",
    subs: "suscriptores al boletín",
    writing: "En publicación",
    live: "Se están abriendo páginas nuevas",
    idle: (t: string) => `Las siguientes páginas se abren a las ${t}`,
    today: "hoy",
    tomorrow: "mañana",
    tz: " (hora de Vietnam)",
    readDraft: "Leer lo publicado",
    draftNote: "Este capítulo se publica poco a poco, en vietnamita. El capítulo completo sale el lunes.",
    reachedEnd: "Has llegado a la página más reciente.",
    words: (w: number, t: number) => `${w.toLocaleString("es-ES")} / ${t.toLocaleString("es-ES")} palabras`,
    legendNative: "Leer en español",
    legendAlt: "Aún sin traducir al español",
    altNote: (l: string) =>
      l === "en" ? "Disponible en inglés · traducción al español en curso" : "Solo en vietnamita · traducción en curso",
    weekAlt: "Próxima semana · original en vietnamita",
    status: (native: number, released: number) =>
      `La edición en vietnamita va por delante: ${released} capítulos en vietnamita, ${native} en español.`,
  },
} satisfies Record<Lang, unknown>;
